name: epos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  uuid: ^4.5.1
  socket_io_client: ^3.1.2
  cupertino_icons: ^1.0.8
  screenshot: ^3.0.0
  flutter_html: ^3.0.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  permission_handler: ^12.0.1
  bluetooth_print_plus: ^2.4.6
  print_bluetooth_thermal: ^1.1.0
  flutter_bluetooth_printer: ^2.19.0
  flutter_usb_printer: ^0.1.0+1
  flutter_blue_plus: ^1.35.5
  provider: ^6.1.5
  thermal_printer: ^1.0.5
  esc_pos_utils: ^1.1.0
  esc_pos_utils_plus: ^2.0.4
  usb_serial: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  image: ^3.3.0  # Changed from ^4.1.3 to ^3.3.0 for compatibility
  rxdart: ^0.28.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700